# Generated by Django 2.2.5 on 2019-09-24 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dog',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
